name: '@medijobs/release'
author: 'medijobs'
description: 'Run medijobs/release on a repo'
outputs:
  release-tag:
    description: 'The tag that was released on success'
  release-version:
    description: 'The version that was released on success'
branding:
  icon: 'package'
  color: 'blue'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/medijobs/release:1.0.1'

